run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - misspell
    - gosec
    - bodyclose
    - noctx
    - gofmt
    - goimports
  disable:
    - staticcheck

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    check-shadowing: true

  goimports:
    local-prefixes: github.com/mesbahtanvir/focus-notebook/backend

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    - path: mocks/
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
