version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Examines Go source code and reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - unused        # Checks for unused constants, variables, functions and types
    - misspell      # Finds commonly misspelled words
    - gosec         # Security problems
    - bodyclose     # Checks HTTP response body is closed
    - noctx         # Finds sending HTTP request without context.Context
  disable:
    - staticcheck   # Disabled due to style warnings (ST1005, SA1029, etc.)
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      # Exclude test files from certain linters
      - path: "_test\\.go"
        linters:
          - errcheck
          - gosec

      # Exclude mock files
      - path: "mocks/"
        linters:
          - staticcheck
          - errcheck

      # G304 - File path provided as taint input (we validate paths in config loading)
      - path: "internal/config/config\\.go"
        text: "G304"

formatters:
  enable:
    - gofmt         # Checks if code is gofmt-ed
    - goimports     # Checks import statements are formatted
  settings:
    goimports:
      local-prefixes:
        - github.com/mesbahtanvir/focus-notebook/backend

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gosec:
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
      - G304 # File path provided as taint input (we validate paths)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
